[package]
name = "concat_vcf"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true

[dependencies]
fm.workspace = true
anyhow.workspace = true
