import os, sys, logging, subprocess
from typing import Literal
import matplotlib.pyplot as plt
import pandas as pd

from Classes import FileManagement

def missing(
    fm: FileManagement,
    input_name: str,
    save_path_name: str,
    ethnic: str | None = None,
    gender: Literal["Men", "Women"] | None = None
    ) -> None:
    """
    Visualise missing data proportions.
    
    # Args:
    
    **input_name** (str): _Name of the input file._
    
    **save_path_name** (str): _Path to save the visualisations (without suffix and extension)._
    
    # Returns:
    
    **None**
    
    # Generate Files:
    
    **${save_path_name}.imiss**: _Missingness of individuals._
    
    **${save_path_name}.lmiss**: _Missingness of SNPs._
    
    **${save_path_name}_imiss_visualisation.png**: _Visualisation of missingness of individuals._
    
    **${save_path_name}_lmiss_visualisation.png**: _Visualisation of missingness of SNPs._
    """

    logging.info("Calculating proportions of missing data of %s %s data set", ethnic, gender)
    try:
        command = [
            fm.plink, 
            "--bfile", input_name, 
            "--missing", 
            "--out", save_path_name
        ]
        subprocess.run(
            command,
            stdout=subprocess.DEVNULL,
            stderr=None,
            check=True
        )
    except subprocess.CalledProcessError as e:
        logging.error(f"Error calculating proportions of missing data plink: {e}")
        sys.exit(2)
    logging.info("Finished Calculation")
    
    logging.info("Visualising missing data")
    
    # Visualise missingness of individuals.
    logging.info("Visualising missingness of individuals")
    imiss_df = pd.read_csv(f"{input_name}.imiss", sep=r"\s+", usecols=["F_MISS"])

    plt.hist(imiss_df, density=True, bins=20)  
    ## density=True makes bin's raw count divided by the total number of counts and the bin width, 
    ## so that the area under the histogram integrates to 1.
    plt.title(f"Histogram of SNP missingness per individual from {ethnic} {gender} data set")
    plt.xlabel("Individuals' SNP missing rate")
    plt.ylabel("Frequency / Intercept")
    plt.tight_layout()      # Remove whitespace and avoid overlap around the plot.
    plt.savefig(f"{save_path_name}_imiss.png", dpi=300)
    ## clear figure to prevent conflicts.
    plt.clf()
    
    # Visualise missingness of SNPs.
    lmiss_df = pd.read_csv(f"{input_name}.lmiss", engine="c", sep=r"\s+", usecols=["F_MISS"])

    plt.hist(lmiss_df, density=True, bins=20)
    plt.title(f"Histogram of individual missingness per SNP from {ethnic} {gender} data set")
    plt.xlabel("SNPs' individual missing rate")
    plt.ylabel("Frequency / Intercept")
    plt.tight_layout()
    plt.savefig(f"{save_path_name}_lmiss.png", dpi=300)
    plt.clf()

def hardy_weinberg(
    fm: FileManagement,
    input_name: str,
    save_path_name: str,
    ethnic: str | None = None,
    gender: Literal["Men", "Women"] | None = None
) -> None:
    """
    Visualise p-value generated by Hardy Weinberg Equilibrium.
    
    Args:
        **input_name** (str): _Name of the input file._
        **save_path_name** (str): _Path to save the visualisations (without suffix and extension)._
        **ethnic** (str): _Ethnic group of the data set._
        **gender** (str): _Gender of the data set._
    
    Generate Files:
        **${save_path_name}.hwe**: _p-value and other statistical information of Hardy Weinberg Equilibrium._
        **${save_path_name}.png**: _Visualisation of p-value of HWE._
    """
    # Calculate HWE.
    logging.info("Calculating p-value of HWE")
    try:
        command = [
            fm.plink,
            "--bfile", input_name,
            "--hardy",
            "--out", input_name
        ]
        subprocess.run(
            command,
            stdout=subprocess.DEVNULL,
            stderr=None,
            check=True
        )
    except subprocess.CalledProcessError as e:
        logging.error(f"Error running plink: {e}")
        sys.exit(2)
    logging.info("Finished Calculation")
        
    
    # Draw histogram.
    hwe = pd.read_csv(f"{input_name}.hwe", sep=r"\s+", usecols=["P"])
    plt.hist(hwe, bins=10)
    plt.xlabel("p value")
    plt.ylabel("Frequency / Intercept")
    plt.title("Histogram of HWE from {ethnic} {gender} data set")
    plt.savefig(f"{save_path_name}.png", dpi=300)
    
    plt.clf()
    '''
    # Zoomed version. Focusing on the severe deviating SNPs.
    zoomed = pd.read_csv(f"{input_name}_zoomhwe.csv", sep=r"\s+", engine="c", header=None, usecols=[8])
    plt.hist(zoomed, bins=20)
    plt.xlabel("p value")
    plt.ylabel("Frequency / Intercept")
    plt.title(f"Histogram of HWE from {ethnic} {gender} data set: severely deviating SNPs only")
    plt.savefig(f"{save_path_name}_zoomhwe.png", dpi=300)
    '''
    plt.clf()

def minor_allele_frequency(
    fm: FileManagement,
    input_name: str,
    save_path_name: str,
    ethnic: str | None = None,
    gender: Literal["Men", "Women"] | None = None
) -> None:
    """
    Visualise minor allele frequency.

    Args:
        **input_name** (str): _Name of the input file._
        **save_path_name** (str): _Path to save the visualisations (without suffix and extension)._
        **ethnic** (str): _Ethnic group of the data set._
        **gender** (str): _Gender of the data set._
    """
    try:
        command = [
            fm.plink,
            "--bfile", input_name,
            "--freq",
            "--out", save_path_name
        ]
        subprocess.run(
            command,
            stdout=subprocess.DEVNULL,
            stderr=None,
            check=True
        )
    except subprocess.CalledProcessError as e:
        logging.error(f"Error running plink: {e}")
        sys.exit(2)
    logging.info("Finished Calculation")

    freq_file = pd.read_csv(
        f"{input_name}.afreq", sep="\t", engine="pyarrow",usecols=["ALT_FREQS"]
    )

    plt.hist(freq_file["ALT_FREQS"],bins=100,range=[0.000001,1])
    plt.title("MAF check")
    plt.savefig(f"{input_name}.png", dpi=300)
    plt.clf()